Carabus 2.0
Toxu4/RDS.CaraBus pull request #10
Opened 2018-02-26 13:52 UTC by DaniilSokolyuk

2018-02-28 11:40 UTC, sergey-borisenko commented on src/RDS.CaraBus.RabbitMQ/RabbitMQCaraBus.cs
> +        public override async Task SubscribeAsyncImpl(Type messageType, Func<object, CancellationToken, Task> handler, SubscribeOptions subscribeOptions, CancellationToken cancellationToken)
protected

2018-02-28 11:41 UTC, DaniilSokolyuk commented on src/RDS.CaraBus.RabbitMQ/RabbitMQCaraBus.cs
> +        public override async Task SubscribeAsyncImpl(Type messageType, Func<object, CancellationToken, Task> handler, SubscribeOptions subscribeOptions, CancellationToken cancellationToken)
fixed

2018-02-28 11:52 UTC, sergey-borisenko commented on src/RDS.CaraBus/CaraBusBase.cs
> +        public async Task StartAsync()
Create -> Stop -> Start

2018-02-28 13:15 UTC, DaniilSokolyuk commented on src/RDS.CaraBus/CaraBusBase.cs
> +        public async Task StartAsync()
fixes

2018-02-28 13:15 UTC, DaniilSokolyuk commented on src/RDS.CaraBus/CaraBusBase.cs
> +        public async Task StartAsync()
fixed

2018-03-01 16:39 UTC, Toxu4 requested changes

2018-03-01 16:39 UTC, Toxu4 commented on src/RDS.CaraBus.RabbitMQ/RabbitMQCaraBus.cs
> +                DispatchConsumersAsync = true
:+1:

2018-03-01 16:39 UTC, Toxu4 commented on src/RDS.CaraBus.RabbitMQ/RabbitMQCaraBus.cs
> +            var queueName = GetQueueName(messageType, subscribeOptions);
change signature - swap arguments:

`GetQueueName(subscribeOptions, messageType);`

2018-03-01 16:39 UTC, Toxu4 commented on src/RDS.CaraBus/ICarabusStopAsync.cs
> +    interface ICarabusStopAsync
`ICaraBusStopAsync`

2018-03-01 16:39 UTC, Toxu4 commented on src/RDS.CaraBus/Utility/TypeExtensions.cs
> +                if (type == null)
wtf?

`while (type != null)`

2018-03-02 16:39 UTC, merged